#!/bin/bash

# Funkar!
# docker run --rm \
# 	--name namedmount \
# 	-v $(pwd)/mindatakatalog/:/app \
# 	-e DEST=/app/ \
# 	namedmountimg

# Funkar också!
# docker run --rm \
# 	--name namedmount \
# 	-v ./mindatakatalog:/app \
# 	-e DEST=/app/ \
# 	namedmountimg

# Funkar INTE! ARG!
# docker run --rm \
# 	--name namedmount \
# 	-v mindatakatalog/:/app \
# 	-e DEST=/app/ \
# 	namedmountimg

# Funkar!
docker run --rm \
	--name namedmount \
	-v mindatakatalog:/app \
	-e DEST=/app/ \
	namedmountimg

# docker run --rm \
# 	--name namedmount \
# 	-v finnsej:/app \
# 	-e DEST=/app/ \
# 	namedmountimg
