#!/bin/bash

SCRIPT_DIR="$(basename -- $0)"

OVMF_CODE=/usr/share/OVMF/OVMF_CODE_4M.fd

# Copied from /usr/share/OVMF/OVMF_VARS_4M.fd
OVMF_VARS=/usr/share/OVMF/OVMF_VARS_4M.fd

qemu-system-x86_64 \
	-cdrom "$ISO" \
	-daemonize \
	-device usb-ehci \
	-device usb-tablet \
	-device virtio-gpu-pci \
	-drive file=arch-disk1.qcow2,format=qcow2 \
	-drive file=arch-disk2.qcow2,format=qcow2 \
	-drive if=pflash,format=raw,file=arch-ovmf-vars.fd \
	-drive if=pflash,format=raw,readonly=on,file=/usr/share/OVMF/OVMF_CODE_4M.fd \
	-enable-kvm \
	-m 4G \
	-machine q35 \
	-smp 2
