#!/bin/bash

while true; do
	(
		cd UMariaDB
		docker build -t umariadb:latest .
		docker run -dit --rm --name umariadbcont umariadb:latest
		read -rp "Press ENTER to rebuild..."
		docker stop umariadbcont
	)
done
